### ISSUE TITLE
IP: Add attribute converters

### ISSUE THREAD

**Issue by kyzrfranz** [mzeiher/ce-decorators#4]
I find property <> attribute converters used in [lit-element](https://lit-element.polymer-project.org/guide/properties#conversion) very helpful.

Would you consider integrating something like [this](https://github.com/Polymer/lit-element/blob/fd31a9767a8ec798d5609819e9bb8fcf5440999d/src/lib/updating-element.ts#L36)

PS - if you like the idea but don't have time - I could help ;)

**Comment by mzeiher** [comment]
I'll add it in the next few days

**Comment by mzeiher** [comment]
fixed with 2.6.0
