### ISSUE TITLE
Unable to bundle with rollup

### ISSUE THREAD

**Issue by ilteoood** [mzeiher/ce-decorators#5]
Hi, thanks for this amazing library.
Bundling it with rollup, I obtain this error:

Error: 'ComponentOptions' is not exported by node_modules/ce-decorators/lib/componentoptions.js

Same error with EventEmitter.

How can I fix this?

Thank,
Matteo

**Comment by mzeiher** [comment]
Hi thanks :), is it possible that you post your rollup config? Are you using the ce-decorators in an typescript project with tsc or babel-preset-typescript or in an javascript project with/without babel?

**Comment by mike-airola** [comment]
Hi, I would like to second this Issue. An example of how babel is supposed to be set up with rollup and tsc would be really helpful for me :)

**Comment by ilteoood** [comment]
Hi @mzeiher, this is my rollup confiruation:

`
import resolve from "rollup-plugin-node-resolve";
import serve from "rollup-plugin-serve";
import livereload from "rollup-plugin-livereload";
import typescriptPlugin from "rollup-plugin-typescript";
import typescript from "typescript";
import litSass from "@ponday/rollup-plugin-lit-sass";
import litHtml from "rollup-plugin-lit-html";

export default {
  input: "src/test/test.ts",
  output: {
    file: "./dist/test.js",
    format: "esm",
  },
  plugins: [
    litSass(),
    litHtml(),
    resolve({
      customResolveOptions: {
        moduleDirectory: "node_modules",
      },
    }),
    typescriptPlugin({
      exclude: "node_modules/**",
      importHelpers: true,
      typescript,
    }),
    serve({
      contentBase: "./",
      historyApiFallback: true,
      host: "localhost",
      open: true,
      port: 8764,
    }),
    livereload(),
  ],
  sourcemap: true,
  treeshake: true,
};

`

While this is my tsconfig.json

`
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "newLine": "LF",
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": false,
    "strict": true,

    "lib": [
      "dom",
      "dom.iterable",
      "esnext",
      "esnext.array",
      "esnext.asynciterable",
      "esnext.intl",
      "esnext.symbol"
    ],
    "moduleResolution": "node",
    "module": "esnext",
    "target": "esnext",
    "rootDir": "src",
    "outDir": "dist",
    "declaration": true,
    "declarationDir": "dist"
  },
  "include": ["src/**/*"],
  "exclude": [
    "node_modules",
    "src/demo*/**/*",
    "src/*/**/*"
  ]
}

`

**Comment by mzeiher** [comment]
fixed in 2.6.1, problem was named exports in index.ts/js -> changed to wildcard now it works :)
